### PR TITLE
 Update depedencies with security risk

### PR DESCRIPTION
**Pull request by SerekKiri**
Not sure which branch so I picked master

### CODE REVIEW

**Comment by samuelmale** [comment]
Could you squash your commits into one? 

https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by SerekKiri** [comment]
You mean that i should make one new commit and delete these two? I'm not sure how to do this and I can't find this in this tips

**Comment by SerekKiri** [comment]
@samuelmale should be good right now! 😄

**Comment by samuelmale** [comment]
Revamp your commit message to suit the conventions here : https://wiki.openmrs.org/display/docs/Pull+Request+Tips

to some thing like `Ticket_Title: Description of an overview for what you made` eg. `GCI-111: Removed unused import from foo.java file`

**Comment by SerekKiri** [comment]
Closing. Fixed PR: https://github.com/openmrs/openmrs-module-oauth2/pull/20

**Pull request closed without merging**
